"""signal_pipeline

Revision ID: 702e0d3fb7c8
Revises: c49e9ec9fbd4
Create Date: 2026-03-19 07:27:39.804883

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "702e0d3fb7c8"
down_revision: str | Sequence[str] | None = "c49e9ec9fbd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("finding_type", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("contributing_signal_ids", sa.JSON(), nullable=False),
        sa.Column("affected_entity_ids", sa.JSON(), nullable=False),
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id", name="uq_finding_id"),
    )
    op.create_index(
        "ix_finding_user_status", "findings", ["user_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_findings_finding_type"), "findings", ["finding_type"], unique=False
    )
    op.create_index(op.f("ix_findings_user_id"), "findings", ["user_id"], unique=False)
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("scorer_version", sa.String(length=20), nullable=False),
        sa.Column("signal_count", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scan_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_score_user_domain_time",
        "scores",
        ["user_id", "domain", "calculated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_scores_user_id"), "scores", ["user_id"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.String(length=32), nullable=False),
        sa.Column("signal_type", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("entity_value", sa.String(length=512), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.String(length=512), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("recommended_action", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id", name="uq_signal_id"),
    )
    op.create_index(
        "ix_signal_user_status", "signals", ["user_id", "status"], unique=False
    )
    op.create_index(
        "ix_signal_user_type", "signals", ["user_id", "signal_type"], unique=False
    )
    op.create_index(
        op.f("ix_signals_signal_type"), "signals", ["signal_type"], unique=False
    )
    op.create_index(op.f("ix_signals_status"), "signals", ["status"], unique=False)
    op.create_index(op.f("ix_signals_user_id"), "signals", ["user_id"], unique=False)
    op.create_index(
        "ix_asset_user_verified", "assets", ["user_id", "is_verified"], unique=False
    )
    op.create_unique_constraint(
        "uq_asset_user_type_value", "assets", ["user_id", "entity_type", "value"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_asset_user_type_value", "assets", type_="unique")
    op.drop_index("ix_asset_user_verified", table_name="assets")
    op.drop_index(op.f("ix_signals_user_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_status"), table_name="signals")
    op.drop_index(op.f("ix_signals_signal_type"), table_name="signals")
    op.drop_index("ix_signal_user_type", table_name="signals")
    op.drop_index("ix_signal_user_status", table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_scores_user_id"), table_name="scores")
    op.drop_index("ix_score_user_domain_time", table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_findings_user_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_finding_type"), table_name="findings")
    op.drop_index("ix_finding_user_status", table_name="findings")
    op.drop_table("findings")
    # ### end Alembic commands ###
