"""auth_and_assets

Revision ID: c49e9ec9fbd4
Revises: dca500496033
Create Date: 2026-03-18 22:47:15.701943

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c49e9ec9fbd4"
down_revision: str | Sequence[str] | None = "dca500496033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
