"""fix_auth_models

Revision ID: dca500496033
Revises: 42527804aad7
Create Date: 2026-03-18 22:39:11.512995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dca500496033"
down_revision: str | Sequence[str] | None = "42527804aad7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_tokens", sa.Column("used_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "auth_tokens",
        sa.Column("requested_from_ip", sa.String(length=45), nullable=True),
    )
    op.alter_column(
        "auth_tokens",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "auth_tokens",
        "code_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.create_index(
        "ix_auth_token_email_hash", "auth_tokens", ["email", "code_hash"], unique=False
    )
    op.drop_constraint(
        op.f("auth_tokens_user_id_fkey"), "auth_tokens", type_="foreignkey"
    )
    op.drop_column("auth_tokens", "user_id")
    op.drop_column("auth_tokens", "created_at")
    op.drop_column("auth_tokens", "is_used")
    op.add_column(
        "users", sa.Column("last_sign_in_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("stripe_subscription_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "privacy_policy_accepted_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.alter_column(
        "users",
        "stripe_customer_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_users_stripe_customer_id"),
        "users",
        ["stripe_customer_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_stripe_customer_id"), table_name="users")
    op.alter_column(
        "users",
        "stripe_customer_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("users", "privacy_policy_accepted_at")
    op.drop_column("users", "stripe_subscription_id")
    op.drop_column("users", "last_sign_in_at")
    op.add_column(
        "auth_tokens",
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "auth_tokens",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "auth_tokens",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("auth_tokens_user_id_fkey"), "auth_tokens", "users", ["user_id"], ["id"]
    )
    op.drop_index("ix_auth_token_email_hash", table_name="auth_tokens")
    op.alter_column(
        "auth_tokens",
        "code_hash",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "auth_tokens",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("auth_tokens", "requested_from_ip")
    op.drop_column("auth_tokens", "used_at")
    # ### end Alembic commands ###
