"""drop_asset_user_fk

Revision ID: e0dffe5ea597
Revises: 702e0d3fb7c8
Create Date: 2026-03-19 07:43:54.906299

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0dffe5ea597"
down_revision: str | Sequence[str] | None = "702e0d3fb7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("assets_user_id_fkey"), "assets", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("assets_user_id_fkey"), "assets", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
