"""add_scan_events_table

Revision ID: f93c39dc7f48
Revises: a7b8c9d0e1f2
Create Date: 2026-04-02 07:44:24.033237

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f93c39dc7f48"
down_revision: str | Sequence[str] | None = "a7b8c9d0e1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scan_events_event_type"), "scan_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_scan_events_scan_id"), "scan_events", ["scan_id"], unique=False
    )
    op.create_index(op.f("ix_scan_events_ts"), "scan_events", ["ts"], unique=False)
    op.create_index(
        op.f("ix_scan_events_user_id"), "scan_events", ["user_id"], unique=False
    )
    op.drop_index(
        op.f("ix_discovered_account_upload"), table_name="discovered_accounts"
    )
    op.create_index(
        op.f("ix_discovered_accounts_upload_id"),
        "discovered_accounts",
        ["upload_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discovered_accounts_user_id"),
        "discovered_accounts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_discovered_accounts_user_id"), table_name="discovered_accounts"
    )
    op.drop_index(
        op.f("ix_discovered_accounts_upload_id"), table_name="discovered_accounts"
    )
    op.create_index(
        op.f("ix_discovered_account_upload"),
        "discovered_accounts",
        ["upload_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_scan_events_user_id"), table_name="scan_events")
    op.drop_index(op.f("ix_scan_events_ts"), table_name="scan_events")
    op.drop_index(op.f("ix_scan_events_scan_id"), table_name="scan_events")
    op.drop_index(op.f("ix_scan_events_event_type"), table_name="scan_events")
    op.drop_table("scan_events")
    # ### end Alembic commands ###
