# scripts/seed_service_registry.py
"""
Seed script for the service_registry table.

Usage:
    python -m scripts.seed_service_registry

Idempotent: uses INSERT ... ON CONFLICT DO UPDATE so it can be re-run safely.
Also loads scripts/custom_services.json if it exists (entries added via
`python -m scripts.validate_services`).
"""

import asyncio
import json
import uuid
from pathlib import Path

from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    create_async_engine,
)
from sqlalchemy.orm import sessionmaker

from backend.app.core.config import settings
from backend.app.db.models.email_accounts import ServiceRegistry

# ---------------------------------------------------------------------------
# Service catalog  (~200 entries)
# Each entry: (service_name, display_name, category, common_domains, login_url, password_reset_url)
# ---------------------------------------------------------------------------
SERVICES: list[tuple[str, str, str, list[str], str | None, str | None]] = [
    # =========================================================================
    # SOCIAL / COMMUNICATION
    # =========================================================================
    (
        "google",
        "Google",
        "social",
        ["google.com", "accounts.google.com", "no-reply.accounts.google.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "facebook",
        "Facebook",
        "social",
        ["facebook.com", "facebookmail.com", "meta.com"],
        "https://www.facebook.com/login",
        "https://www.facebook.com/login/identify",
    ),
    (
        "twitter",
        "X (Twitter)",
        "social",
        ["twitter.com", "x.com"],
        "https://twitter.com/login",
        "https://twitter.com/account/begin_password_reset",
    ),
    (
        "instagram",
        "Instagram",
        "social",
        ["instagram.com", "mail.instagram.com"],
        "https://www.instagram.com/accounts/login",
        "https://www.instagram.com/accounts/password/reset",
    ),
    (
        "linkedin",
        "LinkedIn",
        "social",
        ["linkedin.com", "e.linkedin.com", "em.linkedin.com"],
        "https://www.linkedin.com/login",
        "https://www.linkedin.com/uas/request-password-reset",
    ),
    (
        "reddit",
        "Reddit",
        "social",
        ["reddit.com", "redditmail.com"],
        "https://www.reddit.com/login",
        "https://www.reddit.com/password",
    ),
    (
        "discord",
        "Discord",
        "social",
        ["discord.com", "discordapp.com"],
        "https://discord.com/login",
        "https://discord.com/reset",
    ),
    (
        "snapchat",
        "Snapchat",
        "social",
        ["snapchat.com"],
        "https://accounts.snapchat.com/accounts/login",
        "https://accounts.snapchat.com/accounts/password_reset_request",
    ),
    (
        "tiktok",
        "TikTok",
        "social",
        ["tiktok.com"],
        "https://www.tiktok.com/login",
        None,
    ),
    (
        "pinterest",
        "Pinterest",
        "social",
        ["pinterest.com"],
        "https://www.pinterest.com/login",
        "https://www.pinterest.com/password/reset",
    ),
    (
        "tumblr",
        "Tumblr",
        "social",
        ["tumblr.com"],
        "https://www.tumblr.com/login",
        "https://www.tumblr.com/forgot_password",
    ),
    (
        "mastodon",
        "Mastodon",
        "social",
        ["mastodon.social", "mastodon.online"],
        "https://mastodon.social/auth/sign_in",
        "https://mastodon.social/auth/password/new",
    ),
    (
        "bluesky",
        "Bluesky",
        "social",
        ["bsky.app", "bsky.social"],
        "https://bsky.app",
        None,
    ),
    (
        "threads",
        "Threads",
        "social",
        ["threads.net"],
        "https://www.threads.net/login",
        None,
    ),
    (
        "nextdoor",
        "Nextdoor",
        "social",
        ["nextdoor.com", "email.nextdoor.com"],
        "https://nextdoor.com/login",
        "https://nextdoor.com/forgot_password",
    ),
    (
        "telegram",
        "Telegram",
        "social",
        ["telegram.org"],
        "https://web.telegram.org",
        None,
    ),
    (
        "whatsapp",
        "WhatsApp",
        "social",
        ["whatsapp.com"],
        "https://web.whatsapp.com",
        None,
    ),
    ("signal", "Signal", "social", ["signal.org"], "https://signal.org", None),
    ("line", "LINE", "social", ["line.me"], "https://account.line.biz/login", None),
    (
        "wechat",
        "WeChat",
        "social",
        ["wechat.com", "weixin.qq.com"],
        "https://wx.qq.com",
        None,
    ),
    (
        "meetup",
        "Meetup",
        "social",
        ["meetup.com"],
        "https://secure.meetup.com/login",
        "https://secure.meetup.com/forgot_password",
    ),
    (
        "quora",
        "Quora",
        "social",
        ["quora.com"],
        "https://www.quora.com/",
        "https://www.quora.com/forgot_password",
    ),
    (
        "flickr",
        "Flickr",
        "social",
        ["flickr.com"],
        "https://identity.flickr.com/login",
        "https://login.yahoo.com/forgot",
    ),
    (
        "vimeo",
        "Vimeo",
        "social",
        ["vimeo.com"],
        "https://vimeo.com/log_in",
        "https://vimeo.com/forgot_password",
    ),
    (
        "devto",
        "DEV Community",
        "social",
        ["dev.to"],
        "https://dev.to/enter",
        "https://dev.to/password_resets/new",
    ),
    # =========================================================================
    # E-COMMERCE / RETAIL
    # =========================================================================
    (
        "amazon",
        "Amazon",
        "ecommerce",
        [
            "amazon.com",
            "amazon.co.uk",
            "amazon.de",
            "amazon.fr",
            "amazon.ca",
            "amazon.com.au",
        ],
        "https://www.amazon.com/ap/signin",
        "https://www.amazon.com/ap/forgotpassword",
    ),
    (
        "ebay",
        "eBay",
        "ecommerce",
        ["ebay.com", "ebay.co.uk", "ebay.de", "ebay.com.au"],
        "https://signin.ebay.com/ws/eBayISAPI.dll?SignIn",
        "https://signin.ebay.com/ws/eBayISAPI.dll?ForgotPassword",
    ),
    (
        "etsy",
        "Etsy",
        "ecommerce",
        ["etsy.com"],
        "https://www.etsy.com/signin",
        "https://www.etsy.com/forgot_password",
    ),
    (
        "shopify",
        "Shopify",
        "ecommerce",
        ["shopify.com", "myshopify.com"],
        "https://accounts.shopify.com/login",
        "https://accounts.shopify.com/lookup",
    ),
    (
        "walmart",
        "Walmart",
        "ecommerce",
        ["walmart.com"],
        "https://www.walmart.com/account/login",
        "https://www.walmart.com/account/forgot-password",
    ),
    (
        "target",
        "Target",
        "ecommerce",
        ["target.com"],
        "https://www.target.com/account/signin",
        "https://www.target.com/account/forgot-password",
    ),
    (
        "bestbuy",
        "Best Buy",
        "ecommerce",
        ["bestbuy.com"],
        "https://www.bestbuy.com/identity/global/signin",
        "https://www.bestbuy.com/identity/global/forgotpassword",
    ),
    (
        "wayfair",
        "Wayfair",
        "ecommerce",
        ["wayfair.com"],
        "https://www.wayfair.com/v/account/login",
        "https://www.wayfair.com/v/account/forgot_password",
    ),
    (
        "aliexpress",
        "AliExpress",
        "ecommerce",
        ["aliexpress.com"],
        "https://login.aliexpress.com",
        None,
    ),
    ("wish", "Wish", "ecommerce", ["wish.com"], "https://www.wish.com/login", None),
    (
        "mercari",
        "Mercari",
        "ecommerce",
        ["mercari.com"],
        "https://www.mercari.com/login",
        "https://www.mercari.com/us/forgot_password",
    ),
    (
        "poshmark",
        "Poshmark",
        "ecommerce",
        ["poshmark.com"],
        "https://poshmark.com/login",
        "https://poshmark.com/forgot_password",
    ),
    ("depop", "Depop", "ecommerce", ["depop.com"], "https://www.depop.com/login", None),
    (
        "toogoodtogo",
        "Too Good To Go",
        "ecommerce",
        ["toogoodtogo.com"],
        "https://www.toogoodtogo.com/",
        None,
    ),
    (
        "asos",
        "ASOS",
        "ecommerce",
        ["asos.com"],
        "https://my.asos.com/my-account/login",
        "https://my.asos.com/my-account/forgot-password",
    ),
    (
        "nike",
        "Nike",
        "ecommerce",
        ["nike.com"],
        "https://www.nike.com/login",
        "https://www.nike.com/help/a/forgot-password",
    ),
    (
        "adidas",
        "Adidas",
        "ecommerce",
        ["adidas.com"],
        "https://www.adidas.com/us/account-login",
        None,
    ),
    (
        "zara",
        "Zara",
        "ecommerce",
        ["zara.com"],
        "https://www.zara.com/us/en/logon",
        None,
    ),
    (
        "hm",
        "H&M",
        "ecommerce",
        ["hm.com"],
        "https://www2.hm.com/en_us/member/login.html",
        "https://www2.hm.com/en_us/member/forgot-password.html",
    ),
    (
        "stockx",
        "StockX",
        "ecommerce",
        ["stockx.com"],
        "https://stockx.com/login",
        "https://stockx.com/forgot-password",
    ),
    ("goat", "GOAT", "ecommerce", ["goat.com"], "https://www.goat.com/login", None),
    (
        "newegg",
        "Newegg",
        "ecommerce",
        ["newegg.com"],
        "https://secure.newegg.com/login",
        "https://secure.newegg.com/forgot-password",
    ),
    (
        "costco",
        "Costco",
        "ecommerce",
        ["costco.com"],
        "https://www.costco.com/LogonForm",
        "https://www.costco.com/ResetPasswordForm",
    ),
    (
        "ikea",
        "IKEA",
        "ecommerce",
        ["ikea.com"],
        "https://www.ikea.com/us/en/profile/login",
        None,
    ),
    (
        "apple_store",
        "Apple Store",
        "ecommerce",
        ["apple.com", "appleid.apple.com"],
        "https://appleid.apple.com",
        "https://iforgot.apple.com",
    ),
    # =========================================================================
    # FINANCE / BANKING / CRYPTO
    # =========================================================================
    (
        "paypal",
        "PayPal",
        "finance",
        ["paypal.com", "e.paypal.com", "paypal.co.uk"],
        "https://www.paypal.com/signin",
        "https://www.paypal.com/authflow/password-recovery",
    ),
    (
        "stripe",
        "Stripe",
        "finance",
        ["stripe.com"],
        "https://dashboard.stripe.com/login",
        "https://dashboard.stripe.com/login/forgot-password",
    ),
    (
        "coinbase",
        "Coinbase",
        "finance",
        ["coinbase.com"],
        "https://login.coinbase.com",
        "https://login.coinbase.com/forgot-password",
    ),
    (
        "revolut",
        "Revolut",
        "finance",
        ["revolut.com"],
        "https://app.revolut.com/sign-in",
        None,
    ),
    (
        "wise",
        "Wise (TransferWise)",
        "finance",
        ["wise.com", "transferwise.com"],
        "https://wise.com/login",
        "https://wise.com/help/articles/2978084",
    ),
    (
        "venmo",
        "Venmo",
        "finance",
        ["venmo.com"],
        "https://account.venmo.com",
        "https://account.venmo.com/forgot-password",
    ),
    (
        "cashapp",
        "Cash App",
        "finance",
        ["cash.app", "square.com"],
        "https://cash.app/login",
        None,
    ),
    (
        "robinhood",
        "Robinhood",
        "finance",
        ["robinhood.com"],
        "https://robinhood.com/login",
        "https://robinhood.com/password-reset",
    ),
    (
        "interactiveinvestor",
        "Interactive Investor",
        "finance",
        ["ii.co.uk", "interactiveinvestor.com"],
        "https://www.ii.co.uk/",
        None,
    ),
    (
        "klarna",
        "Klarna",
        "finance",
        ["klarna.com"],
        "https://app.klarna.com/login",
        None,
    ),
    (
        "afterpay",
        "Afterpay",
        "finance",
        ["afterpay.com"],
        "https://portal.afterpay.com/au/login",
        "https://portal.afterpay.com/au/forgot-password",
    ),
    ("chime", "Chime", "finance", ["chime.com"], "https://app.chime.com/login", None),
    ("monzo", "Monzo", "finance", ["monzo.com"], "https://monzo.com/login", None),
    ("n26", "N26", "finance", ["n26.com"], "https://app.n26.com/login", None),
    (
        "schwab",
        "Charles Schwab",
        "finance",
        ["schwab.com"],
        "https://client.schwab.com/Login/SignOn",
        "https://client.schwab.com/Login/ForgotPassword",
    ),
    (
        "fidelity",
        "Fidelity",
        "finance",
        ["fidelity.com"],
        "https://digital.fidelity.com/ftgw/digital/login",
        "https://digital.fidelity.com/ftgw/digital/forgotpassword",
    ),
    (
        "binance",
        "Binance",
        "finance",
        ["binance.com"],
        "https://accounts.binance.com/en/login",
        "https://accounts.binance.com/en/forgetPassword",
    ),
    (
        "kraken",
        "Kraken",
        "finance",
        ["kraken.com"],
        "https://www.kraken.com/sign-in",
        "https://www.kraken.com/forgot-password",
    ),
    (
        "etrade",
        "E*TRADE",
        "finance",
        ["etrade.com"],
        "https://us.etrade.com/e/t/user/login",
        None,
    ),
    (
        "quickbooks",
        "QuickBooks",
        "finance",
        ["intuit.com", "quickbooks.intuit.com"],
        "https://accounts.intuit.com/index.html",
        "https://accounts.intuit.com/forgot-password",
    ),
    (
        "xero",
        "Xero",
        "finance",
        ["xero.com"],
        "https://login.xero.com",
        "https://login.xero.com/forgot-password",
    ),
    # =========================================================================
    # STREAMING / ENTERTAINMENT
    # =========================================================================
    (
        "netflix",
        "Netflix",
        "streaming",
        ["netflix.com"],
        "https://www.netflix.com/login",
        "https://www.netflix.com/loginHelp",
    ),
    (
        "spotify",
        "Spotify",
        "streaming",
        ["spotify.com"],
        "https://accounts.spotify.com/login",
        "https://accounts.spotify.com/password-reset",
    ),
    (
        "apple",
        "Apple / Apple ID",
        "streaming",
        ["apple.com", "id.apple.com", "appleid.apple.com"],
        "https://appleid.apple.com",
        "https://iforgot.apple.com",
    ),
    (
        "youtube",
        "YouTube",
        "streaming",
        ["youtube.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "twitch",
        "Twitch",
        "streaming",
        ["twitch.tv"],
        "https://www.twitch.tv/login",
        "https://passport.twitch.tv/forgot_password",
    ),
    (
        "disney_plus",
        "Disney+",
        "streaming",
        ["disneyplus.com", "go.com"],
        "https://www.disneyplus.com/login",
        "https://www.disneyplus.com/reset-password",
    ),
    (
        "hulu",
        "Hulu",
        "streaming",
        ["hulu.com"],
        "https://auth.hulu.com/web/login",
        "https://auth.hulu.com/web/password/forgot",
    ),
    (
        "hbo_max",
        "Max (HBO)",
        "streaming",
        ["hbomax.com", "max.com"],
        "https://www.max.com/sign-in",
        "https://www.max.com/forgot-password",
    ),
    (
        "paramount_plus",
        "Paramount+",
        "streaming",
        ["paramountplus.com", "cbs.com"],
        "https://www.paramountplus.com/account/signin",
        "https://www.paramountplus.com/account/forget-password",
    ),
    (
        "peacock",
        "Peacock",
        "streaming",
        ["peacocktv.com"],
        "https://www.peacocktv.com/signin",
        "https://www.peacocktv.com/forgot-password",
    ),
    (
        "apple_tv",
        "Apple TV+",
        "streaming",
        ["tv.apple.com"],
        "https://appleid.apple.com",
        "https://iforgot.apple.com",
    ),
    (
        "crunchyroll",
        "Crunchyroll",
        "streaming",
        ["crunchyroll.com"],
        "https://sso.crunchyroll.com/login",
        "https://sso.crunchyroll.com/forgot-password",
    ),
    (
        "soundcloud",
        "SoundCloud",
        "streaming",
        ["soundcloud.com"],
        "https://soundcloud.com/signin",
        "https://soundcloud.com/forgot-password",
    ),
    (
        "tidal",
        "TIDAL",
        "streaming",
        ["tidal.com"],
        "https://login.tidal.com",
        "https://login.tidal.com/forgot",
    ),
    (
        "deezer",
        "Deezer",
        "streaming",
        ["deezer.com"],
        "https://www.deezer.com/login",
        "https://www.deezer.com/forgot",
    ),
    (
        "audible",
        "Audible",
        "streaming",
        ["audible.com"],
        "https://www.audible.com/ap/signin",
        "https://www.audible.com/ap/forgotpassword",
    ),
    (
        "plex",
        "Plex",
        "streaming",
        ["plex.tv"],
        "https://app.plex.tv/desktop/#!/signin",
        "https://app.plex.tv/desktop/#!/forgotPassword",
    ),
    (
        "youtube_music",
        "YouTube Music",
        "streaming",
        ["music.youtube.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "amazon_prime",
        "Amazon Prime Video",
        "streaming",
        ["primevideo.com"],
        "https://www.primevideo.com/ap/signin",
        "https://www.amazon.com/ap/forgotpassword",
    ),
    (
        "mubi",
        "MUBI",
        "streaming",
        ["mubi.com"],
        "https://mubi.com/en/sign_in",
        "https://mubi.com/en/password/new",
    ),
    # =========================================================================
    # PRODUCTIVITY / CLOUD / COLLABORATION
    # =========================================================================
    (
        "microsoft",
        "Microsoft / Office 365",
        "productivity",
        ["microsoft.com", "live.com", "outlook.com", "hotmail.com", "office.com"],
        "https://login.microsoftonline.com",
        "https://account.live.com/password/reset",
    ),
    (
        "dropbox",
        "Dropbox",
        "productivity",
        ["dropbox.com"],
        "https://www.dropbox.com/login",
        "https://www.dropbox.com/forgot",
    ),
    (
        "slack",
        "Slack",
        "productivity",
        ["slack.com"],
        "https://slack.com/signin",
        "https://slack.com/forgot-password",
    ),
    (
        "notion",
        "Notion",
        "productivity",
        ["notion.so", "mail.notion.so"],
        "https://www.notion.so/login",
        None,
    ),
    (
        "atlassian",
        "Atlassian (Jira / Confluence)",
        "productivity",
        ["atlassian.com", "atlassian.net"],
        "https://id.atlassian.com",
        "https://id.atlassian.com/login/resetpassword",
    ),
    (
        "zoom",
        "Zoom",
        "productivity",
        ["zoom.us"],
        "https://zoom.us/signin",
        "https://zoom.us/forgot_password",
    ),
    (
        "adobe",
        "Adobe Creative Cloud",
        "productivity",
        ["adobe.com"],
        "https://account.adobe.com",
        "https://account.adobe.com/security",
    ),
    (
        "figma",
        "Figma",
        "productivity",
        ["figma.com"],
        "https://www.figma.com/login",
        "https://www.figma.com/forgot-password",
    ),
    (
        "canva",
        "Canva",
        "productivity",
        ["canva.com"],
        "https://www.canva.com/login",
        "https://www.canva.com/forgot-password",
    ),
    (
        "trello",
        "Trello",
        "productivity",
        ["trello.com"],
        "https://trello.com/login",
        "https://trello.com/forgot",
    ),
    (
        "asana",
        "Asana",
        "productivity",
        ["asana.com"],
        "https://app.asana.com/-/login",
        "https://app.asana.com/-/account_recovery_request",
    ),
    (
        "monday",
        "Monday.com",
        "productivity",
        ["monday.com"],
        "https://auth.monday.com/login",
        "https://auth.monday.com/forgot_password",
    ),
    (
        "clickup",
        "ClickUp",
        "productivity",
        ["clickup.com"],
        "https://app.clickup.com/login",
        "https://app.clickup.com/forgot",
    ),
    (
        "airtable",
        "Airtable",
        "productivity",
        ["airtable.com"],
        "https://airtable.com/login",
        "https://airtable.com/forgot-password",
    ),
    (
        "evernote",
        "Evernote",
        "productivity",
        ["evernote.com"],
        "https://www.evernote.com/Login.action",
        "https://www.evernote.com/ForgotPassword.action",
    ),
    (
        "calendly",
        "Calendly",
        "productivity",
        ["calendly.com"],
        "https://calendly.com/login",
        "https://calendly.com/forgot_password",
    ),
    (
        "docusign",
        "DocuSign",
        "productivity",
        ["docusign.com", "docusign.net"],
        "https://account.docusign.com",
        "https://account.docusign.com/forgotpassword",
    ),
    (
        "box",
        "Box",
        "productivity",
        ["box.com"],
        "https://account.box.com/login",
        "https://account.box.com/reset_password",
    ),
    (
        "google_workspace",
        "Google Workspace",
        "productivity",
        ["workspace.google.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "hubspot",
        "HubSpot",
        "productivity",
        ["hubspot.com"],
        "https://app.hubspot.com/login",
        "https://app.hubspot.com/login/forgot-password",
    ),
    (
        "salesforce",
        "Salesforce",
        "productivity",
        ["salesforce.com"],
        "https://login.salesforce.com",
        "https://login.salesforce.com/secur/forgotpassword.jsp",
    ),
    (
        "zendesk",
        "Zendesk",
        "productivity",
        ["zendesk.com"],
        "https://www.zendesk.com/login",
        "https://support.zendesk.com/hc/en-us/requests/new",
    ),
    (
        "intercom",
        "Intercom",
        "productivity",
        ["intercom.com", "intercom.io"],
        "https://app.intercom.com/admins/sign_in",
        "https://app.intercom.com/admins/password/new",
    ),
    (
        "webex",
        "Cisco Webex",
        "productivity",
        ["webex.com", "cisco.com"],
        "https://web.webex.com/sign-in",
        None,
    ),
    (
        "teams",
        "Microsoft Teams",
        "productivity",
        ["teams.microsoft.com"],
        "https://login.microsoftonline.com",
        "https://account.live.com/password/reset",
    ),
    (
        "linear",
        "Linear",
        "productivity",
        ["linear.app"],
        "https://linear.app/login",
        None,
    ),
    (
        "basecamp",
        "Basecamp",
        "productivity",
        ["basecamp.com"],
        "https://launchpad.37signals.com/signin",
        "https://launchpad.37signals.com/sessions/forgot_password",
    ),
    # =========================================================================
    # DEVELOPER TOOLS / CLOUD INFRASTRUCTURE
    # =========================================================================
    (
        "github",
        "GitHub",
        "developer",
        ["github.com"],
        "https://github.com/login",
        "https://github.com/password_reset",
    ),
    (
        "gitlab",
        "GitLab",
        "developer",
        ["gitlab.com"],
        "https://gitlab.com/users/sign_in",
        "https://gitlab.com/users/password/new",
    ),
    (
        "bitbucket",
        "Bitbucket",
        "developer",
        ["bitbucket.org"],
        "https://bitbucket.org/account/signin",
        "https://bitbucket.org/account/forgot-password",
    ),
    (
        "aws",
        "Amazon Web Services",
        "developer",
        ["aws.amazon.com", "amazonaws.com"],
        "https://console.aws.amazon.com",
        "https://www.amazon.com/ap/forgotpassword",
    ),
    (
        "gcp",
        "Google Cloud Platform",
        "developer",
        ["cloud.google.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "azure",
        "Microsoft Azure",
        "developer",
        ["azure.microsoft.com", "portal.azure.com"],
        "https://login.microsoftonline.com",
        "https://account.live.com/password/reset",
    ),
    (
        "cloudflare",
        "Cloudflare",
        "developer",
        ["cloudflare.com"],
        "https://dash.cloudflare.com/login",
        "https://dash.cloudflare.com/forgot-password",
    ),
    ("vercel", "Vercel", "developer", ["vercel.com"], "https://vercel.com/login", None),
    (
        "netlify",
        "Netlify",
        "developer",
        ["netlify.com"],
        "https://app.netlify.com/login",
        "https://app.netlify.com/forgot",
    ),
    (
        "heroku",
        "Heroku",
        "developer",
        ["heroku.com"],
        "https://id.heroku.com/login",
        "https://id.heroku.com/forgot_password",
    ),
    (
        "digitalocean",
        "DigitalOcean",
        "developer",
        ["digitalocean.com"],
        "https://cloud.digitalocean.com/login",
        "https://cloud.digitalocean.com/forgot_password",
    ),
    (
        "linode_akamai",
        "Linode / Akamai Cloud",
        "developer",
        ["linode.com", "akamai.com"],
        "https://login.linode.com/login",
        "https://login.linode.com/forgot/password",
    ),
    (
        "railway",
        "Railway",
        "developer",
        ["railway.app"],
        "https://railway.app/login",
        None,
    ),
    (
        "render",
        "Render",
        "developer",
        ["render.com"],
        "https://dashboard.render.com/login",
        "https://dashboard.render.com/forgot-password",
    ),
    ("fly_io", "Fly.io", "developer", ["fly.io"], "https://fly.io/app/sign-in", None),
    (
        "docker",
        "Docker Hub",
        "developer",
        ["docker.com", "hub.docker.com"],
        "https://login.docker.com",
        "https://login.docker.com/u/reset-password",
    ),
    (
        "npm",
        "npm",
        "developer",
        ["npmjs.com"],
        "https://www.npmjs.com/login",
        "https://www.npmjs.com/forgot",
    ),
    (
        "pypi",
        "PyPI",
        "developer",
        ["pypi.org"],
        "https://pypi.org/account/login",
        "https://pypi.org/account/request-password-reset",
    ),
    (
        "jetbrains",
        "JetBrains",
        "developer",
        ["jetbrains.com"],
        "https://account.jetbrains.com/login",
        "https://account.jetbrains.com/forgot-password",
    ),
    (
        "sentry",
        "Sentry",
        "developer",
        ["sentry.io"],
        "https://sentry.io/auth/login",
        "https://sentry.io/account/recover",
    ),
    (
        "datadog",
        "Datadog",
        "developer",
        ["datadoghq.com"],
        "https://app.datadoghq.com/account/login",
        "https://app.datadoghq.com/account/forgot_password",
    ),
    (
        "supabase",
        "Supabase",
        "developer",
        ["supabase.com", "supabase.io"],
        "https://app.supabase.com",
        None,
    ),
    (
        "firebase",
        "Firebase / Google",
        "developer",
        ["firebase.google.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "circleci",
        "CircleCI",
        "developer",
        ["circleci.com"],
        "https://circleci.com/vcs-authorize",
        None,
    ),
    (
        "github_actions",
        "GitHub Actions",
        "developer",
        ["github.com"],
        "https://github.com/login",
        "https://github.com/password_reset",
    ),
    (
        "postman",
        "Postman",
        "developer",
        ["postman.com", "getpostman.com"],
        "https://identity.getpostman.com/login",
        "https://identity.getpostman.com/forgot-password",
    ),
    # =========================================================================
    # TRAVEL / HOSPITALITY
    # =========================================================================
    (
        "airbnb",
        "Airbnb",
        "travel",
        ["airbnb.com"],
        "https://www.airbnb.com/login",
        "https://www.airbnb.com/forgot_password",
    ),
    (
        "booking_com",
        "Booking.com",
        "travel",
        ["booking.com"],
        "https://account.booking.com/sign-in",
        "https://account.booking.com/auth/oauth2/reset-password",
    ),
    ("uber", "Uber", "travel", ["uber.com"], "https://auth.uber.com/v2/", None),
    ("lyft", "Lyft", "travel", ["lyft.com"], "https://account.lyft.com/auth", None),
    (
        "expedia",
        "Expedia",
        "travel",
        ["expedia.com"],
        "https://www.expedia.com/user/login",
        "https://www.expedia.com/user/forgotpassword",
    ),
    (
        "kayak",
        "KAYAK",
        "travel",
        ["kayak.com"],
        "https://www.kayak.com/user/login",
        None,
    ),
    (
        "tripadvisor",
        "Tripadvisor",
        "travel",
        ["tripadvisor.com"],
        "https://www.tripadvisor.com/members/sign-in",
        None,
    ),
    (
        "hotels_com",
        "Hotels.com",
        "travel",
        ["hotels.com"],
        "https://www.hotels.com/user/login",
        "https://www.hotels.com/user/forgotpassword",
    ),
    (
        "hilton",
        "Hilton Honors",
        "travel",
        ["hilton.com"],
        "https://www.hilton.com/en/hilton-honors/sign-in",
        "https://www.hilton.com/en/hilton-honors/forgot-password",
    ),
    (
        "marriott",
        "Marriott Bonvoy",
        "travel",
        ["marriott.com"],
        "https://www.marriott.com/sign-in.mi",
        "https://www.marriott.com/sign-in.mi?method=forgotPassword",
    ),
    (
        "delta",
        "Delta Air Lines",
        "travel",
        ["delta.com"],
        "https://www.delta.com/us/en/sign-in/overview",
        "https://www.delta.com/us/en/sign-in/forgot-password",
    ),
    (
        "united",
        "United Airlines",
        "travel",
        ["united.com"],
        "https://www.united.com/ual/en/us/account/account.aspx",
        None,
    ),
    (
        "american_airlines",
        "American Airlines",
        "travel",
        ["aa.com", "americanairlines.com"],
        "https://www.aa.com/login.do",
        "https://www.aa.com/forgotPassword.do",
    ),
    (
        "vrbo",
        "VRBO",
        "travel",
        ["vrbo.com"],
        "https://www.vrbo.com/user/login",
        "https://www.vrbo.com/user/forgotpassword",
    ),
    (
        "enterprise",
        "Enterprise Rent-A-Car",
        "travel",
        ["enterprise.com"],
        "https://www.enterprise.com/en/car-rental/profile/login.html",
        None,
    ),
    # =========================================================================
    # FOOD / DELIVERY
    # =========================================================================
    (
        "doordash",
        "DoorDash",
        "food",
        ["doordash.com"],
        "https://www.doordash.com/auth/login",
        "https://www.doordash.com/auth/forgot-password",
    ),
    (
        "ubereats",
        "Uber Eats",
        "food",
        ["ubereats.com"],
        "https://auth.uber.com/v2/",
        None,
    ),
    (
        "grubhub",
        "Grubhub",
        "food",
        ["grubhub.com"],
        "https://www.grubhub.com/login",
        "https://www.grubhub.com/forgot-password",
    ),
    (
        "instacart",
        "Instacart",
        "food",
        ["instacart.com"],
        "https://www.instacart.com/accounts/login",
        "https://www.instacart.com/accounts/forgot_password",
    ),
    (
        "hellofresh",
        "HelloFresh",
        "food",
        ["hellofresh.com"],
        "https://www.hellofresh.com/account/login",
        "https://www.hellofresh.com/account/forgot-password",
    ),
    (
        "opentable",
        "OpenTable",
        "food",
        ["opentable.com"],
        "https://www.opentable.com/login",
        "https://www.opentable.com/forgot-password",
    ),
    (
        "yelp",
        "Yelp",
        "food",
        ["yelp.com"],
        "https://www.yelp.com/login",
        "https://www.yelp.com/forgot_password",
    ),
    (
        "deliveroo",
        "Deliveroo",
        "food",
        ["deliveroo.com", "deliveroo.co.uk"],
        "https://deliveroo.co.uk/login",
        "https://deliveroo.co.uk/login#forgot-password",
    ),
    (
        "just_eat",
        "Just Eat",
        "food",
        ["just-eat.co.uk", "just-eat.com"],
        "https://www.just-eat.co.uk/account/login",
        None,
    ),
    # =========================================================================
    # GAMING
    # =========================================================================
    (
        "steam",
        "Steam",
        "gaming",
        ["steampowered.com", "valvesoftware.com"],
        "https://store.steampowered.com/login",
        "https://help.steampowered.com/en/wizard/HelpWithLoginInfo",
    ),
    (
        "epic_games",
        "Epic Games",
        "gaming",
        ["epicgames.com"],
        "https://www.epicgames.com/id/login",
        "https://www.epicgames.com/id/forgot-password",
    ),
    (
        "playstation",
        "PlayStation Network",
        "gaming",
        ["playstation.com", "sony.com"],
        "https://my.account.sony.com/central/signin",
        "https://my.account.sony.com/central/forgot-password",
    ),
    (
        "xbox",
        "Xbox / Microsoft Gaming",
        "gaming",
        ["xbox.com", "xboxlive.com"],
        "https://login.live.com",
        "https://account.live.com/password/reset",
    ),
    (
        "nintendo",
        "Nintendo",
        "gaming",
        ["nintendo.com", "nintendo.net"],
        "https://accounts.nintendo.com/login",
        "https://accounts.nintendo.com/forgot_password",
    ),
    (
        "blizzard",
        "Battle.net (Blizzard)",
        "gaming",
        ["blizzard.com", "battle.net"],
        "https://battle.net/login",
        "https://battle.net/login/en/forgot-password",
    ),
    (
        "riot_games",
        "Riot Games",
        "gaming",
        ["riotgames.com"],
        "https://auth.riotgames.com/login",
        "https://auth.riotgames.com/login#forgot-password",
    ),
    (
        "ubisoft",
        "Ubisoft Connect",
        "gaming",
        ["ubisoft.com", "ubi.com"],
        "https://connect.ubisoft.com/login",
        "https://connect.ubisoft.com/forgot-password",
    ),
    (
        "ea",
        "EA / Origin",
        "gaming",
        ["ea.com", "origin.com"],
        "https://signin.ea.com",
        "https://signin.ea.com/p/originX/forgotPassword",
    ),
    (
        "gog",
        "GOG.com",
        "gaming",
        ["gog.com"],
        "https://login.gog.com",
        "https://login.gog.com/forgotPassword",
    ),
    (
        "roblox",
        "Roblox",
        "gaming",
        ["roblox.com"],
        "https://www.roblox.com/login",
        "https://www.roblox.com/login/forgot-password",
    ),
    (
        "minecraft",
        "Minecraft / Mojang",
        "gaming",
        ["minecraft.net", "mojang.com"],
        "https://login.minecraft.net",
        "https://login.minecraft.net/forgot",
    ),
    (
        "twitch_gaming",
        "Twitch",
        "gaming",
        ["twitch.tv"],
        "https://www.twitch.tv/login",
        "https://passport.twitch.tv/forgot_password",
    ),
    # =========================================================================
    # HEALTH / FITNESS / WELLNESS
    # =========================================================================
    (
        "myfitnesspal",
        "MyFitnessPal",
        "health",
        ["myfitnesspal.com"],
        "https://www.myfitnesspal.com/user/login",
        "https://www.myfitnesspal.com/user/forgot_password",
    ),
    (
        "strava",
        "Strava",
        "health",
        ["strava.com"],
        "https://www.strava.com/login",
        "https://www.strava.com/password/new",
    ),
    (
        "peloton",
        "Peloton",
        "health",
        ["onepeloton.com"],
        "https://members.onepeloton.com/login",
        "https://members.onepeloton.com/forgot-password",
    ),
    (
        "garmin",
        "Garmin Connect",
        "health",
        ["garmin.com"],
        "https://sso.garmin.com/sso/signin",
        "https://sso.garmin.com/sso/forgotPassword",
    ),
    (
        "fitbit",
        "Fitbit / Google",
        "health",
        ["fitbit.com"],
        "https://www.fitbit.com/login/transferpage",
        None,
    ),
    (
        "calm",
        "Calm",
        "health",
        ["calm.com"],
        "https://www.calm.com/login",
        "https://www.calm.com/forgot-password",
    ),
    (
        "headspace",
        "Headspace",
        "health",
        ["headspace.com"],
        "https://my.headspace.com/signin",
        "https://my.headspace.com/forgot-password",
    ),
    ("noom", "Noom", "health", ["noom.com"], "https://web.noom.com/login", None),
    (
        "zwift",
        "Zwift",
        "health",
        ["zwift.com"],
        "https://zwift.com/sign-in",
        "https://zwift.com/forgot-password",
    ),
    # =========================================================================
    # SECURITY / PASSWORD MANAGERS / VPN
    # =========================================================================
    (
        "1password",
        "1Password",
        "security",
        ["1password.com"],
        "https://my.1password.com/signin",
        "https://my.1password.com/forgot-sign-in-details",
    ),
    (
        "lastpass",
        "LastPass",
        "security",
        ["lastpass.com"],
        "https://lastpass.com/?ac=1",
        "https://lastpass.com/recover.php",
    ),
    (
        "bitwarden",
        "Bitwarden",
        "security",
        ["bitwarden.com"],
        "https://vault.bitwarden.com/#/login",
        "https://vault.bitwarden.com/#/recover-2fa",
    ),
    (
        "dashlane",
        "Dashlane",
        "security",
        ["dashlane.com"],
        "https://app.dashlane.com",
        "https://app.dashlane.com/#/master-password-reset",
    ),
    (
        "keeper",
        "Keeper Security",
        "security",
        ["keepersecurity.com"],
        "https://keepersecurity.com/vault/",
        "https://keepersecurity.com/forgot-password",
    ),
    (
        "nordvpn",
        "NordVPN",
        "security",
        ["nordvpn.com"],
        "https://my.nordaccount.com/login",
        "https://my.nordaccount.com/forgot-password",
    ),
    (
        "expressvpn",
        "ExpressVPN",
        "security",
        ["expressvpn.com"],
        "https://www.expressvpn.com/sign-in",
        "https://www.expressvpn.com/forgot-password",
    ),
    (
        "mullvad",
        "Mullvad VPN",
        "security",
        ["mullvad.net"],
        "https://mullvad.net/en/account/login",
        None,
    ),
    (
        "proton",
        "Proton (Mail / VPN)",
        "security",
        ["proton.me", "protonmail.com", "protonvpn.com"],
        "https://account.proton.me/login",
        "https://account.proton.me/reset-password",
    ),
    # =========================================================================
    # EDUCATION / LEARNING
    # =========================================================================
    (
        "coursera",
        "Coursera",
        "education",
        ["coursera.org"],
        "https://www.coursera.org/login",
        "https://www.coursera.org/account/forgot-password",
    ),
    (
        "udemy",
        "Udemy",
        "education",
        ["udemy.com"],
        "https://www.udemy.com/join/login-popup",
        "https://www.udemy.com/join/reset-password",
    ),
    (
        "duolingo",
        "Duolingo",
        "education",
        ["duolingo.com"],
        "https://www.duolingo.com/login",
        "https://www.duolingo.com/forgot-password",
    ),
    (
        "khan_academy",
        "Khan Academy",
        "education",
        ["khanacademy.org"],
        "https://www.khanacademy.org/login",
        "https://www.khanacademy.org/forgot-password",
    ),
    (
        "skillshare",
        "Skillshare",
        "education",
        ["skillshare.com"],
        "https://www.skillshare.com/en/login",
        "https://www.skillshare.com/en/forgot-password",
    ),
    (
        "pluralsight",
        "Pluralsight",
        "education",
        ["pluralsight.com"],
        "https://app.pluralsight.com/id/signin",
        "https://app.pluralsight.com/id/forgotpassword",
    ),
    (
        "linkedin_learning",
        "LinkedIn Learning",
        "education",
        ["linkedin.com"],
        "https://www.linkedin.com/learning/login",
        "https://www.linkedin.com/uas/request-password-reset",
    ),
    (
        "brilliant",
        "Brilliant",
        "education",
        ["brilliant.org"],
        "https://brilliant.org/login",
        "https://brilliant.org/forgot-password",
    ),
    (
        "edx",
        "edX",
        "education",
        ["edx.org"],
        "https://courses.edx.org/login",
        "https://courses.edx.org/password_reset",
    ),
    (
        "codecademy",
        "Codecademy",
        "education",
        ["codecademy.com"],
        "https://www.codecademy.com/login",
        "https://www.codecademy.com/forgot",
    ),
    (
        "datacamp",
        "DataCamp",
        "education",
        ["datacamp.com"],
        "https://app.datacamp.com/account/login",
        "https://app.datacamp.com/account/forgot-password",
    ),
    (
        "chegg",
        "Chegg",
        "education",
        ["chegg.com"],
        "https://www.chegg.com/login",
        "https://www.chegg.com/forgot-password",
    ),
    # =========================================================================
    # NEWS / MEDIA / PUBLISHING
    # =========================================================================
    ("medium", "Medium", "media", ["medium.com"], "https://medium.com/m/signin", None),
    (
        "substack",
        "Substack",
        "media",
        ["substack.com"],
        "https://substack.com/sign-in",
        None,
    ),
    (
        "patreon",
        "Patreon",
        "media",
        ["patreon.com"],
        "https://www.patreon.com/login",
        "https://www.patreon.com/passwordReset",
    ),
    (
        "wordpress",
        "WordPress.com",
        "media",
        ["wordpress.com"],
        "https://wordpress.com/log-in",
        "https://wordpress.com/lostpassword",
    ),
    (
        "squarespace",
        "Squarespace",
        "media",
        ["squarespace.com"],
        "https://account.squarespace.com/log-in",
        "https://account.squarespace.com/password-reset",
    ),
    (
        "wix",
        "Wix",
        "media",
        ["wix.com"],
        "https://users.wix.com/signin",
        "https://users.wix.com/forgot-password",
    ),
    ("ghost", "Ghost", "media", ["ghost.org"], "https://ghost.org/signin", None),
    (
        "beehiiv",
        "beehiiv",
        "media",
        ["beehiiv.com"],
        "https://app.beehiiv.com/login",
        "https://app.beehiiv.com/forgot-password",
    ),
    (
        "kickstarter",
        "Kickstarter",
        "media",
        ["kickstarter.com"],
        "https://www.kickstarter.com/login",
        "https://www.kickstarter.com/profile/forgot_password",
    ),
    (
        "indiegogo",
        "Indiegogo",
        "media",
        ["indiegogo.com"],
        "https://www.indiegogo.com/login",
        "https://www.indiegogo.com/forgot-password",
    ),
    (
        "nyt",
        "The New York Times",
        "media",
        ["nytimes.com"],
        "https://myaccount.nytimes.com/auth/login",
        "https://myaccount.nytimes.com/auth/forgot-password",
    ),
    (
        "wsj",
        "The Wall Street Journal",
        "media",
        ["wsj.com"],
        "https://accounts.wsj.com/login",
        "https://accounts.wsj.com/forgot-password",
    ),
    # =========================================================================
    # DESIGN / CREATIVE
    # =========================================================================
    (
        "behance",
        "Behance",
        "creative",
        ["behance.net"],
        "https://www.behance.net/",
        "https://www.adobe.com/account/sign-in.supportt.html",
    ),
    (
        "dribbble",
        "Dribbble",
        "creative",
        ["dribbble.com"],
        "https://dribbble.com/session/new",
        "https://dribbble.com/users/password/new",
    ),
    (
        "deviantart",
        "DeviantArt",
        "creative",
        ["deviantart.com"],
        "https://www.deviantart.com/users/login",
        "https://www.deviantart.com/users/forgotpassword",
    ),
    (
        "unsplash",
        "Unsplash",
        "creative",
        ["unsplash.com"],
        "https://unsplash.com/login",
        "https://unsplash.com/forgot",
    ),
    (
        "shutterstock",
        "Shutterstock",
        "creative",
        ["shutterstock.com"],
        "https://accounts.shutterstock.com/login",
        "https://accounts.shutterstock.com/signup/forgot",
    ),
    # =========================================================================
    # CLOUD STORAGE / BACKUP
    # =========================================================================
    (
        "google_drive",
        "Google Drive",
        "storage",
        ["drive.google.com"],
        "https://accounts.google.com",
        "https://accounts.google.com/signin/recovery",
    ),
    (
        "onedrive",
        "OneDrive",
        "storage",
        ["onedrive.live.com"],
        "https://login.microsoftonline.com",
        "https://account.live.com/password/reset",
    ),
    (
        "icloud",
        "iCloud",
        "storage",
        ["icloud.com", "me.com"],
        "https://www.icloud.com",
        "https://iforgot.apple.com",
    ),
    (
        "mega",
        "MEGA",
        "storage",
        ["mega.nz", "mega.co.nz"],
        "https://mega.nz/login",
        "https://mega.nz/recovery",
    ),
    (
        "backblaze",
        "Backblaze",
        "storage",
        ["backblaze.com"],
        "https://secure.backblaze.com/user_signin.htm",
        "https://secure.backblaze.com/user_forgotten_password.htm",
    ),
    # =========================================================================
    # SHOPPING / MARKETPLACE (additional)
    # =========================================================================
    (
        "threadup",
        "thredUP",
        "ecommerce",
        ["thredup.com"],
        "https://www.thredup.com/account/login",
        "https://www.thredup.com/account/forgot-password",
    ),
    (
        "redbubble",
        "Redbubble",
        "ecommerce",
        ["redbubble.com"],
        "https://www.redbubble.com/auth/login",
        "https://www.redbubble.com/auth/forgot_password",
    ),
    (
        "society6",
        "Society6",
        "ecommerce",
        ["society6.com"],
        "https://society6.com/account/login",
        "https://society6.com/account/forgot_password",
    ),
    (
        "swappa",
        "Swappa",
        "ecommerce",
        ["swappa.com"],
        "https://swappa.com/login",
        "https://swappa.com/forgot-password",
    ),
    # =========================================================================
    # MISC / OTHER POPULAR SERVICES
    # =========================================================================
    (
        "eventbrite",
        "Eventbrite",
        "events",
        ["eventbrite.com"],
        "https://www.eventbrite.com/login",
        "https://www.eventbrite.com/forgot-password",
    ),
    (
        "meetup_events",
        "Meetup",
        "events",
        ["meetup.com"],
        "https://secure.meetup.com/login",
        "https://secure.meetup.com/forgot_password",
    ),
    (
        "ancestry",
        "Ancestry",
        "lifestyle",
        ["ancestry.com"],
        "https://www.ancestry.com/account/signin",
        "https://www.ancestry.com/account/credentials-input",
    ),
    (
        "23andme",
        "23andMe",
        "lifestyle",
        ["23andme.com"],
        "https://you.23andme.com/login",
        "https://you.23andme.com/reset",
    ),
    (
        "duolingo_plus",
        "Duolingo Plus",
        "education",
        ["duolingo.com"],
        "https://www.duolingo.com/login",
        "https://www.duolingo.com/forgot-password",
    ),
    (
        "ringcentral",
        "RingCentral",
        "productivity",
        ["ringcentral.com"],
        "https://login.ringcentral.com",
        "https://login.ringcentral.com/forgot-password",
    ),
    (
        "surveymonkey",
        "SurveyMonkey",
        "productivity",
        ["surveymonkey.com"],
        "https://www.surveymonkey.com/user/sign-in",
        "https://www.surveymonkey.com/user/forgot-password",
    ),
    (
        "typeform",
        "Typeform",
        "productivity",
        ["typeform.com"],
        "https://admin.typeform.com/login",
        "https://admin.typeform.com/forgot-password",
    ),
    (
        "mailchimp",
        "Mailchimp",
        "marketing",
        ["mailchimp.com"],
        "https://login.mailchimp.com",
        "https://login.mailchimp.com/forgot/",
    ),
    (
        "sendgrid_user",
        "Twilio SendGrid",
        "marketing",
        ["sendgrid.com", "twilio.com"],
        "https://app.sendgrid.com/login",
        "https://app.sendgrid.com/reset",
    ),
    (
        "buffer",
        "Buffer",
        "marketing",
        ["buffer.com"],
        "https://login.buffer.com",
        "https://login.buffer.com/forgot",
    ),
    (
        "hootsuite",
        "Hootsuite",
        "marketing",
        ["hootsuite.com"],
        "https://hootsuite.com/login",
        "https://hootsuite.com/forgot-password",
    ),
    (
        "namecheap",
        "Namecheap",
        "developer",
        ["namecheap.com"],
        "https://www.namecheap.com/myaccount/login",
        "https://www.namecheap.com/myaccount/forgot-password",
    ),
    (
        "godaddy",
        "GoDaddy",
        "developer",
        ["godaddy.com"],
        "https://sso.godaddy.com/login",
        "https://sso.godaddy.com/forgot",
    ),
    (
        "squarespace_domains",
        "Squarespace Domains",
        "developer",
        ["squarespace.com"],
        "https://account.squarespace.com/log-in",
        "https://account.squarespace.com/password-reset",
    ),
    (
        "pagerduty",
        "PagerDuty",
        "developer",
        ["pagerduty.com"],
        "https://app.pagerduty.com/sign_in",
        "https://app.pagerduty.com/forgot",
    ),
    (
        "twilio",
        "Twilio",
        "developer",
        ["twilio.com"],
        "https://console.twilio.com/login",
        "https://console.twilio.com/forgot-password",
    ),
    (
        "segment",
        "Segment / Twilio",
        "developer",
        ["segment.com"],
        "https://app.segment.com/login",
        "https://app.segment.com/forgot-password",
    ),
    (
        "mixpanel",
        "Mixpanel",
        "developer",
        ["mixpanel.com"],
        "https://mixpanel.com/login",
        "https://mixpanel.com/forgot-password",
    ),
    (
        "amplitude",
        "Amplitude",
        "developer",
        ["amplitude.com"],
        "https://app.amplitude.com/login",
        "https://app.amplitude.com/forgot-password",
    ),
]


def _load_custom() -> list[tuple[str, str, str, list[str], str | None, str | None]]:
    custom_file = Path(__file__).parent / "custom_services.json"
    if not custom_file.exists():
        return []
    entries = json.loads(custom_file.read_text())
    return [
        (
            e["service_name"],
            e["display_name"],
            e["category"],
            e["common_domains"],
            e.get("login_url"),
            e.get("password_reset_url"),
        )
        for e in entries
    ]


async def seed() -> None:
    engine = create_async_engine(settings.database_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    all_services = SERVICES + _load_custom()

    async with async_session() as session:
        for (
            service_name,
            display_name,
            category,
            common_domains,
            login_url,
            password_reset_url,
        ) in all_services:
            stmt = (
                pg_insert(ServiceRegistry)
                .values(
                    id=uuid.uuid4(),
                    service_name=service_name,
                    display_name=display_name,
                    category=category,
                    common_domains=common_domains,
                    login_url=login_url,
                    password_reset_url=password_reset_url,
                    is_active=True,
                )
                .on_conflict_do_update(
                    constraint="uq_service_registry_name",
                    set_={
                        "display_name": display_name,
                        "category": category,
                        "common_domains": common_domains,
                        "login_url": login_url,
                        "password_reset_url": password_reset_url,
                        "is_active": True,
                    },
                )
            )
            await session.execute(stmt)

        await session.commit()

    await engine.dispose()
    custom = _load_custom()
    print(
        f"Seeded {len(SERVICES)} built-in + {len(custom)} custom = {len(all_services)} services."
    )


if __name__ == "__main__":
    asyncio.run(seed())
