import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy — Zima",
  description: "How Zima collects, uses, and protects your personal data.",
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-white">{title}</h2>
      <div className="text-sm text-slate-400 leading-relaxed space-y-2">{children}</div>
    </section>
  )
}

export default function PrivacyPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-sm text-slate-500">Last updated: April 2026</p>
      </div>

      <p className="text-sm text-slate-400 leading-relaxed">
        Zima (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) provides an identity protection platform that helps
        you discover, monitor, and reduce your digital exposure. This Privacy Policy explains what data
        we collect, how we use it, and your rights as a user.
      </p>

      <Section title="1. Data We Collect">
        <p>
          <strong className="text-slate-300">Identity assets:</strong> Email addresses, usernames, and
          phone numbers you provide during onboarding or add to your account. These are the subjects of
          all scans Zima performs.
        </p>
        <p>
          <strong className="text-slate-300">Authentication data:</strong> We use one-time passcodes
          (OTP) only. We never store passwords. Authentication tokens are short-lived JWTs stored in
          httpOnly cookies.
        </p>
        <p>
          <strong className="text-slate-300">Scan results:</strong> Signals, findings, and scores
          generated by scanning your verified assets against third-party data sources. This includes
          breach records, public profile data, and credential exposure indicators.
        </p>
        <p>
          <strong className="text-slate-300">Uploaded files:</strong> mbox files you optionally upload
          to discover accounts registered to your email. These are processed and then deleted. We do not
          retain raw email content beyond what is needed to complete processing.
        </p>
        <p>
          <strong className="text-slate-300">Usage and audit data:</strong> IP address, user agent, and
          event timestamps for security audit logging. This data is retained for 90 days.
        </p>
        <p>
          <strong className="text-slate-300">Billing data:</strong> Payment information is processed
          exclusively by Stripe. We store only your Stripe customer ID and subscription status — never
          raw card details.
        </p>
      </Section>

      <Section title="2. How We Use Your Data">
        <p>We use your data solely to provide the Zima service:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li>Running identity scans against breach and exposure databases</li>
          <li>Generating risk scores, findings, and remediation guidance</li>
          <li>Sending breach alert emails when new exposures are detected</li>
          <li>Processing billing and subscription management via Stripe</li>
          <li>Maintaining security audit logs for your account</li>
        </ul>
        <p>
          We do not sell your data. We do not use your data for advertising. We do not share your data
          with third parties except as necessary to operate the service (e.g. Stripe for payments,
          breach data providers for scanning).
        </p>
      </Section>

      <Section title="3. Data Retention">
        <p>
          Scan results, signals, and findings are retained for the lifetime of your account. Audit
          events are retained for 90 days. mbox file content is deleted after processing completes.
        </p>
        <p>
          You can export all your data at any time from your account settings. You can delete your
          account and all associated data at any time — deletion is permanent and irreversible.
        </p>
      </Section>

      <Section title="4. Third-Party Providers">
        <p>
          Zima queries third-party data providers (breach databases, OSINT sources) on your behalf
          using your verified assets as query parameters. These queries are subject to each
          provider&apos;s own terms and privacy policies.
        </p>
        <p>
          We share only the minimum data necessary to complete each query (typically a hashed or plain
          email address, username, or phone number depending on the provider&apos;s API requirements).
        </p>
      </Section>

      <Section title="5. Your Rights (GDPR / UK GDPR)">
        <p>If you are in the EU or UK, you have the right to:</p>
        <ul className="list-disc list-inside space-y-1 pl-2">
          <li>Access the personal data we hold about you (via the data export feature)</li>
          <li>Rectification of inaccurate data</li>
          <li>Erasure of your data (via account deletion)</li>
          <li>Data portability (via JSON export)</li>
          <li>Object to processing</li>
        </ul>
        <p>To exercise any right, use the account settings page or contact us at the address below.</p>
      </Section>

      <Section title="6. Security">
        <p>
          We use industry-standard security practices including TLS encryption in transit, AES-256-GCM
          encryption for stored API keys and sensitive fields, OTP-only authentication, and security
          headers on all responses. We do not store passwords.
        </p>
      </Section>

      <Section title="7. Cookies">
        <p>
          Zima uses a single httpOnly, Secure, SameSite=Strict session cookie for authentication. We do
          not use tracking cookies, analytics cookies, or third-party advertising cookies.
        </p>
      </Section>

      <Section title="8. Changes to This Policy">
        <p>
          We may update this policy from time to time. Material changes will be communicated via email
          to your verified address. Continued use of Zima after changes constitutes acceptance of the
          updated policy.
        </p>
      </Section>

      <Section title="9. Contact">
        <p>
          For privacy-related questions or requests, contact us at{" "}
          <span className="text-violet-400">privacy@zima.app</span>.
        </p>
      </Section>
    </div>
  )
}
